### ISSUE TITLE
fastMod is incorrect

### ISSUE THREAD

**Issue by Proximyst** [Hydrinity/Hydrinity#1]
`80 % 80 = 0`
`fastMod(80, 80) = 80 & 79 = 64`

These are wildly different and will not work the same at all. It's fine if the divisor is an n such that `n = 2^m, m \in Z`, but that is not the case here. I question the need for `fastMod` at all: the JVM's JIT should be fully able to optimise `n % 2^m` to a bitwise AND operation.

**Comment by KoxSosen** [comment]
First issue @_@

**Comment by budgidiere** [comment]
rip got an issue I guess you have to close up show now @nkomarn :P

**Comment by isebasus** [comment]
o________o

**Comment by nkomarn** [comment]
> `80 % 80 = 0`
> `fastMod(80, 80) = 80 & 79 = 64`
> 
> These are wildly different and will not work the same at all. It's fine if the divisor is an n such that `n = 2^m, m \in Z`, but that is not the case here. I question the need for `fastMod` at all: the JVM's JIT should be fully able to optimise `n % 2^m` to a bitwise AND operation.

You are correct. After running a JMH benchmark w/ Java 11, it appears that there is no need for this method, even when applicable. Using a bitwise AND operation does result in fewer instructions, but this doesn't translate to any notable performance increase over using modulo and certainly is a premature optimization.
